### ISSUE TITLE
Highlighter stops at certain elements

### ISSUE THREAD

**Issue by OsidAbu-alrub** [Gbillington1/OneLine-Chrome-Extension#13]
As shown in the video, the highlight disappears and doesn't continue past the div.

https://user-images.githubusercontent.com/74870723/111631634-4ee3ea80-87fc-11eb-9a4e-a9074f391eda.mp4

**Comment by Gbillington1** [comment]
This has been an issue for a while, it's on my "to fix" list, but Its hard to identify what exactly is going on. Thank's for reporting it, let me know if you have any more info.

**Comment by Gbillington1** [comment]
This issue was caused due to OneLine splitting and attempting to highlight CSS in style tags that are within divs on the page. Fixed in the push to the v2 branch on Feb 14th 2023. Will be a part of the next update once everything is ready
