### ISSUE TITLE
Skipping/jumping multiple rows with long press of the arrow key

### ISSUE THREAD

**Issue by MojoMoe** [Gbillington1/OneLine-Chrome-Extension#14]
Windows 11 OS Build: 22000.613
Google Chrome: Version 101.0.4951.41 (Official Build) (64-bit)

Cannot jump/forward to rows by long-pressing the down arrow key. It only skips one row per press of the key, regardless of long or short press. Let me know if you need more info or if this is by design. Thanks.

**Comment by Gbillington1** [comment]
Thanks for this issue, I haven't added functionality to skip multiple lines w/ a long press, but I like the idea. I'll see what I can do

**Comment by Gbillington1** [comment]
lol didn't mean to close this

**Comment by MojoMoe** [comment]
> Thanks for this issue, I haven't added functionality to skip multiple lines w/ a long press, but I like the idea. I'll see what I can do

No worries at all. Thanks for looking into this 'feature request' I guess lol.

**Comment by Gbillington1** [comment]
This issue has also been fixed for a while in the v2 branch -- not live on the chrome store yet, but it will be in the next update. Thanks for reporting
